[build]
  publish = "dist"
  command = "pnpm install && pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://qznkrrcdvtubcwwldndo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bmtycmNkdnR1YmN3d2xkbmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MTA0OTAsImV4cCI6MjA3NzE4NjQ5MH0.7HZ60y8Lkn8HTUAqm6lITkaTQD7HkKkiAExDUdFzXyg"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200